#!/bin/bash
# AutoForge Summary — Generate post-run summary reports
# Reads TSV + optional findings file, produces markdown summary
#
# Usage: ./summary.sh [results.tsv] [--findings findings.md] [--output summary.md]
#
# Environment:
#   AF_CHANNEL   — Messaging channel (telegram, discord, slack). Default: telegram
#   AF_CHAT_ID   — Chat/group ID for delivery.
#   AF_TOPIC_ID  — Thread/topic ID within the chat.

set -euo pipefail

RESULTS_FILE="${1:-results.tsv}"
shift 1 2>/dev/null || true

# Parse flags
FINDINGS_FILE=""
OUTPUT_FILE=""
SEND_FLAG=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --findings) FINDINGS_FILE="${2:-}"; shift 2 ;;
    --output)   OUTPUT_FILE="${2:-}"; shift 2 ;;
    --send)     SEND_FLAG="yes"; shift ;;
    *)          shift ;;
  esac
done

# Set defaults
FINDINGS_FILE="${FINDINGS_FILE:-}"
OUTPUT_FILE="${OUTPUT_FILE:-$(dirname "$RESULTS_FILE")/$(basename "$RESULTS_FILE" .tsv)-summary.md}"

CHANNEL="${AF_CHANNEL:-telegram}"
CHAT_ID="${AF_CHAT_ID:-}"
TOPIC_ID="${AF_TOPIC_ID:-}"

# --- Validation ---
if [ ! -f "$RESULTS_FILE" ]; then
  echo "Error: Results file not found: $RESULTS_FILE" >&2
  exit 1
fi

# --- Extract Data ---
TOTAL=$(tail -n +2 "$RESULTS_FILE" | wc -l | tr -d ' ')

if [ "$TOTAL" -eq 0 ] 2>/dev/null; then
  echo "Error: No data rows in $RESULTS_FILE" >&2
  exit 1
fi
BEST=$(tail -n +2 "$RESULTS_FILE" | awk -F'\t' '{val=$3; gsub(/%/,"",val); if(val ~ /^[0-9.]+$/ && val+0>max+0)max=val} END{print max+0}')
BEST_ITER=$(tail -n +2 "$RESULTS_FILE" | awk -F'\t' -v best="$BEST" '{val=$3; gsub(/%/,"",val); if(val ~ /^[0-9.]+$/ && val+0==best+0){iter=$1}} END{print iter}')
FIRST_RATE=$(tail -n +2 "$RESULTS_FILE" | head -1 | awk -F'\t' '{val=$3; gsub(/%/,"",val); print val+0}')
LAST_STATUS=$(tail -n +2 "$RESULTS_FILE" | tail -1 | awk -F'\t' '{print $NF}')
IMPROVED=$(tail -n +2 "$RESULTS_FILE" | awk -F'\t' '$NF=="improved" {c++} END{print c+0}')
DISCARD=$(tail -n +2 "$RESULTS_FILE" | awk -F'\t' '$NF=="discard" {c++} END{print c+0}')
RETAINED=$(tail -n +2 "$RESULTS_FILE" | awk -F'\t' '$NF=="retained" {c++} END{print c+0}')

DELTA=$((BEST - FIRST_RATE))

# Determine grade
if [ "$BEST" -eq 100 ] 2>/dev/null; then
  GRADE="🥇 Perfect"
elif [ "$BEST" -ge 90 ] 2>/dev/null; then
  GRADE="🥈 Excellent"
elif [ "$BEST" -ge 75 ] 2>/dev/null; then
  GRADE="🥉 Good"
else
  GRADE="⚠️ Needs Work"
fi

# --- Build Iteration Table ---
ITER_TABLE="| Iter | Summary | Rate | Change | Status |
|------|---------|------|--------|--------|"

while IFS=$'\t' read -r iter summary rate change status rest; do
  icon=""
  case "$status" in
    improved) icon="✅" ;;
    retained) icon="➡️" ;;
    discard)  icon="❌" ;;
    baseline) icon="📍" ;;
    *)        icon="🔹" ;;
  esac
  ITER_TABLE="${ITER_TABLE}
| ${iter} | ${summary} | ${rate} | ${change} | ${icon} ${status} |"
done < <(tail -n +2 "$RESULTS_FILE")

# --- Build Summary ---
cat > "$OUTPUT_FILE" << EOF
# AutoForge Run Summary

## Results: ${GRADE}

| Metric | Value |
|--------|-------|
| Total Iterations | ${TOTAL} |
| Baseline | ${FIRST_RATE}% |
| Best Pass Rate | ${BEST}% (Iter ${BEST_ITER}) |
| Improvement | +${DELTA}% |
| Improved | ${IMPROVED} |
| Retained | ${RETAINED} |
| Discarded | ${DISCARD} |
| Final Status | ${LAST_STATUS} |

## Iteration History

${ITER_TABLE}

## Key Changes
EOF

# Add top 3 improvements
tail -n +2 "$RESULTS_FILE" | awk -F'\t' '$NF=="improved" {printf "- **Iter %s** (%s): %s\n", $1, $3, $4}' >> "$OUTPUT_FILE"

# Add findings if present
if [ -n "$FINDINGS_FILE" ] && [ -f "$FINDINGS_FILE" ]; then
  {
    echo ""
    echo "## Findings"
    echo ""
    cat "$FINDINGS_FILE"
  } >> "$OUTPUT_FILE"
fi

# Add regression notes
REGRESSIONS=$(tail -n +2 "$RESULTS_FILE" | awk -F'\t' '$NF=="discard" {printf "- **Iter %s**: %s (→ %s)\n", $1, $4, $3}')
if [ -n "$REGRESSIONS" ]; then
  cat >> "$OUTPUT_FILE" << EOF

## Regressions (Discarded)
${REGRESSIONS}
EOF
fi

{
  echo ""
  echo "---"
  echo "_Generated by AutoForge v2_"
} >> "$OUTPUT_FILE"

echo "Summary written: $OUTPUT_FILE"

# --- Send to channel if requested ---
if [ "$SEND_FLAG" = "yes" ] && [ -n "$CHAT_ID" ] && command -v openclaw &>/dev/null; then
  # Send a compact version
  COMPACT="📋 *AutoForge Summary*

${GRADE} — ${FIRST_RATE}% → ${BEST}% (+${DELTA}%)
${TOTAL} iterations: ✅${IMPROVED} ➡️${RETAINED} ❌${DISCARD}

Full report: $(basename "$OUTPUT_FILE")"

  CMD="openclaw message send --channel ${CHANNEL} --target ${CHAT_ID}"
  if [ -n "$TOPIC_ID" ]; then
    CMD="${CMD} --thread-id ${TOPIC_ID}"
  fi
  $CMD --message "$COMPACT"
fi
